const SEND_UID ="SEND_UID";
const DRAWER = "DRAWER";
const REGISTER_USER = "REGISTER_USER";
const CANDIDATE_LIST = "CANDIDATE_LIST";
const EDIT_CANDIDATE = "EDIT_CANDIDATE";
const EDIT_USER = "EDIT_USER";
const DIALOG = "DIALOG";
const DELETE_USER = "DELETE_USER";
const IS_VOTED = "IS_VOTED";

export default 
{SEND_UID,
DRAWER,
REGISTER_USER,
CANDIDATE_LIST,
EDIT_CANDIDATE,
EDIT_USER,
DIALOG,
DELETE_USER,
IS_VOTED};